# Generated by Django 4.0.6 on 2022-11-03 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bstore', '0003_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='addtocart',
            field=models.ManyToManyField(blank=True, default=None, related_name='addd', to=settings.AUTH_USER_MODEL),
        ),
    ]
