# Generated by Django 4.0.6 on 2022-11-10 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bstore', '0005_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='requestaddress',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='requests',
            name='requesteduser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requests',
            name='requestphone',
            field=models.IntegerField(default=None),
        ),
    ]
