# Generated by Django 4.0.6 on 2022-11-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bstore', '0006_requests_requestaddress_requests_requesteduser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requests',
            name='requestdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
