# Generated by Django 4.0.6 on 2022-11-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bstore', '0007_requests_finished_requests_requestdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='quote1',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='quote2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='quote3',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
