# Generated by Django 4.0.6 on 2022-11-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bstore', '0008_alter_books_quote1_alter_books_quote2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewards',
            name='rewardbook',
        ),
        migrations.AddField(
            model_name='books',
            name='bookrewards',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='bstore.rewards'),
        ),
    ]
